const atagenRoster = {
  'Anaokulu 3 Yaş': [
    'ADEN DURU AĞCA',
    'ATA OR',
    'ALİ EGE GÜNDOĞDU',
    'EMİR DURSUN',
    'ZEYNEP SERRA ÇAKTI',
    'LEYLA TOKUŞ'
  ],
  'Anaokulu 4 Yaş': [
    'AZRA ÖZTÜRK',
    'ÇAĞAN ALİ SOĞLA',
    'EFLİN DURGUT',
    'ELİF ARYA EROĞLU',
    'GÖKÇE GÜLTEKİN',
    'GÖKTUĞ AYDIN',
    'LEYLA ÇALIK',
    'NİL AĞAN',
    'MUAZ ONUR ASLAN',
    'URAZ ALP KADER',
    'MEVA KAR'
  ],
  'Anaokulu 5 Yaş': [
    'ALİN LİNA GÜLER',
    'ALP ARAS KÜÇÜK',
    'ARYA FİDAN',
    'ASLI YILMAZ',
    'BERRA KARAKAYA',
    'EYMEN AYDEMİR',
    'LİNA MERAL',
    'OĞUZHAN KONCA',
    'UMAY PERA YAMAÇ',
    'ÜLKÜ DEFNE YILMAZ',
    'ZAIN EHAB AHMAD MASOUD'
  ],
  '1-A': [
    'ALİHAN OSMAN KURT',
    'AREL ERTAN',
    'ATA AYDOĞAN',
    'BATUHAN DENİZ KIRILMAZ',
    'DENA KAZEMİ',
    'DERİN SU ŞENTÜRK',
    'ELMAN HASANLOEI',
    'İDİL MİLA İLHAN',
    'KARAN AKTAŞ',
    'SUDE KARTAL',
    'TOPRAK BÜNYAMİN YAMAN',
    'VENUS AKHAVANSADEGHI',
    'SAMADİAN AROUSHA'
  ],
  '2-A': [
    'ALAN ÇİÇEK',
    'BÜŞRA SALTIK',
    'DEFNE DEMİR',
    'ELİF MİLA KOCATAŞ',
    'HANZADE MİLA TEKİN',
    'KAAN ÇAKMAK',
    'KEREM DEMİRCİ',
    'LIANA ESMAEILI',
    'OZAN ERDEM KOÇ',
    'UĞUR DENİZ KIZGIR',
    'YAVUZ ATLAS DEMİR GEZER',
    'YİĞİT HAMZA ÇOBANBAŞI'
  ],
  '3-A': [
    'DEMİR ASAF KAYAPUNAR',
    'DENİZ KAAN AYDIN',
    'DOĞA GÜL',
    'İNCİ CEYLİN FIRTIN',
    'KUZEY YILDIZ',
    'LİNA BİRCE EKER',
    'MARVİN SALMAN',
    'MELİNA YELESER',
    'NEHİR DAYDAŞ',
    'YAĞMUR YÖRUKUL',
    'EBRAR MİNA AKGÜL'
  ],
  '4-A': [
    'DEFNE TÜNAY',
    'ÖZGÜR ŞEN',
    'DENİZ MECİT',
    'EFE GÜNAY',
    'HALİS DEMİR KILIÇ',
    'HAYAT KAYA',
    'MELİSA ALKAN',
    'RABİA CUM',
    'ZEYNEP ERÇEVİK',
    'ZELİŞ GÖKÇE CANDAN',
    'ALYA DİRİCE',
    'ASLAN ALİ SOYLU',
    'ALİ HAKKI'
  ],
  '4-B': [
    'ŞEVVAL KAR',
    'MİLA NAZ AVCI',
    'NEHİR BERRAK ŞENTÜRK',
    'ASLI DİNDAR',
    'AZRA TANEM AKTAŞ',
    'DEFNE AKER',
    'DENİZ BEYAZ',
    'DERİN ELİF SÜLÜN',
    'EGEMEN AYDEMİR',
    'ELİF AYSEL OR',
    'EYLÜL DENİZ KAYABAŞ',
    'FURKAN URAS ERTÜRK',
    'HAMZA TOPRAK KOCAMAN',
    'URAZ KUTAY RAMAZAN',
    'YAĞIZ ASAF KARAKUŞ',
    'ERTUĞRUL TAHAR SALTIK',
    'DESMOND EMMANUEL EMBAYE',
    'BERAT ERAY ÇAĞLAV',
    'YAKUP ÇINAR EKŞİ'
  ]
};

module.exports = { atagenRoster };
